name: ML Pipeline

on: [push, pull_request]

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run tests
      run: |
        pytest tests/ -v
    
    - name: Train and save model
      run: |
        python train.py
    
    - name: Archive model artifacts
      uses: actions/upload-artifact@v3
      with:
        name: trained-model
        path: models/ 
